apiVersion: v1
kind: Namespace
metadata:
  name: pyllama
---
apiVersion: v1
kind: Service
metadata:
  name: pyllama
  namespace: pyllama
  labels:
    app: pyllama
spec:
  type: NodePort
  selector:
    app: pyllama
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30100
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyllama-vol-pvc
  namespace: pyllama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 6Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyllama
  namespace: pyllama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyllama
  template:
    metadata:
      labels:
        app: pyllama
    spec:
      restartPolicy: Always
      initContainers:
      - name: pyllama-init
        image: busybox:latest
        command: ['sh', '-c', "cd data; test -f *.gguf || wget https://gpt4all.io/models/gguf/mistral-7b-instruct-v0.1.Q4_0.gguf"]
        volumeMounts:
        - name: volv
          mountPath: /data
      containers:
      - name: pyllama-container
        image: regulatedd/pyllama:cpu
        volumeMounts:
        - name: volv
          mountPath: /models
        ports:
        - containerPort: 8080
        env:
        - name: MODEL
          value: "/models/mistral-7b-instruct-v0.1.Q4_0.gguf"
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: pyllama-vol-pvc
