apiVersion: v1
kind: Namespace
metadata:
  name: pyllama
---
apiVersion: v1
kind: Service
metadata:
  name: pyllama
  namespace: pyllama
  labels:
    app: pyllama
spec:
  type: NodePort
  selector:
    app: pyllama
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30100
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyllama-vol-pvc
  namespace: pyllama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyllama
  namespace: pyllama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyllama
  template:
    metadata:
      labels:
        app: pyllama
    spec:
      restartPolicy: Always
      containers:
      - name: pyllama-container
        image: regulatedd/pyllama:cpu
        volumeMounts:
        - name: volv
          mountPath: /data
        ports:
        - containerPort: 8080
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: pyllama-vol-pvc
